// Generated by CoffeeScript 1.9.1
(function() {
  var selectSelfmade;

  window.acceptSelfmade = function() {
    return sendForm("#acceptSelfmade", {
      api: "addChallenge",
      cb: function(errors) {
        if (errors.length) {
          return;
        }
        return callApi("deleteEntry", {
          table: "suggested",
          id: $("#selfmadeSelect").val()
        });
      }
    });
  };

  selectSelfmade = function() {
    var i, id, len, prop, ref;
    id = $("#selfmadeSelect").val();
    console.log("selected:", id);
    ref = ["title", "points", "class", "description", "location"];
    for (i = 0, len = ref.length; i < len; i++) {
      prop = ref[i];
      $("#acceptSelfmade >> [name='" + prop + "']").val(suggestedChallenges[id][prop]);
    }
    $("#class-name").text(suggestedChallenges[id].name);
    return $("#teacher-email").text(suggestedChallenges[id].email);
  };

  $('document').ready(function() {
    var first, id;
    first = null;
    for (id in suggestedChallenges) {
      first = id;
      break;
    }
    if (first == null) {
      return;
    }
    $("#selfmadeSelect").val(first);
    $("#selfmadeSelect").change(selectSelfmade);
    selectSelfmade();
    $(".slide-down .slide-down-header").each(function() {
      return $(this).click(function() {
        $(this).siblings(".slide-down-hidden").slideToggle(300);
        $(this).find(".fa").toggleClass("fa-arrow-down");
        return $(this).find(".fa").toggleClass("fa-arrow-up");
      });
    });
  });

}).call(this);
