// Generated by CoffeeScript 1.10.0
(function() {
  var selectSelfmade;

  window.acceptSelfmade = function() {
    return sendForm("#acceptSelfmade", {
      api: "addChallenge",
      cb: function(errors) {
        if (errors.length) {
          return;
        }
        return callApi("deleteEntry", {
          table: "suggested",
          id: $("#selfmadeSelect").val()
        });
      }
    });
  };

  selectSelfmade = function() {
    var i, id, j, len, len1, prop, ref, ref1, ref2, ref3;
    id = $("#selfmadeSelect").val();
    console.log("selected:", id);
    ref = ["title", "points", "class", "description", "location", "extrapoints"];
    for (i = 0, len = ref.length; i < len; i++) {
      prop = ref[i];
      $("#acceptSelfmade [name='" + prop + "']").val((ref1 = suggestedChallenges[id][prop]) != null ? ref1 : "");
    }
    $("#class-name").text(suggestedChallenges[id].name);
    $("#teacher-email").text(suggestedChallenges[id].email);
    $("#allow_continuous_use").text(suggestedChallenges[id].allow_continuous_use ? "Ja" : "Nein");
    $("#dimensions").text(suggestedChallenges[id].dimensions.join(", "));
    ref2 = ["suggested_category", "goals", "duration", "aid"];
    for (j = 0, len1 = ref2.length; j < len1; j++) {
      prop = ref2[j];
      $("#" + prop).text((ref3 = suggestedChallenges[id][prop]) != null ? ref3 : "");
    }
  };

  $('document').ready(function() {
    var first, id;
    first = null;
    for (id in suggestedChallenges) {
      first = id;
      break;
    }
    if (first != null) {
      $("#selfmadeSelect").val(first);
      $("#selfmadeSelect").change(selectSelfmade);
      selectSelfmade();
    }
    $(".slide-down .slide-down-header").each(function() {
      return $(this).click(function() {
        return toggleArrow(this, $(this).siblings(".slide-down-hidden"));
      });
    });
  });

}).call(this);
