// Generated by CoffeeScript 1.9.1
var classSelectChanged, onClassSelectChanged, selectedClass, setClass;

selectedClass = null;

classSelectChanged = [];

setClass = function(newClass) {
  var f, i, len;
  console.log('setClass:', newClass);
  $('.class-' + selectedClass).removeClass('class-selected');
  selectedClass = newClass;
  localStorage.setItem('selectedClass', selectedClass);
  $('.class-value').val(selectedClass);
  $('.class-' + selectedClass).addClass('class-selected');
  for (i = 0, len = classSelectChanged.length; i < len; i++) {
    f = classSelectChanged[i];
    f(selectedClass);
  }
};

onClassSelectChanged = function(f) {
  if (selectedClass != null) {
    f(selectedClass);
  }
  return classSelectChanged.push(f);
};

$('document').ready(function() {
  var classSelect, classes;
  selectedClass = localStorage.getItem('selectedClass');
  classes = [];
  $('#class-select option').each(function(v, a) {
    return classes.push($(a).prop('value'));
  });
  if ((selectedClass == null) || classes.indexOf(selectedClass) === -1) {
    selectedClass = classes[0];
  }
  classSelect = $('#class-select');
  classSelect.val(selectedClass);
  setClass(selectedClass);
  return classSelect.on('change', function() {
    setClass(this.value);
  });
});
