// Generated by CoffeeScript 1.10.0
(function() {
  var classSelectChanged, setClass;

  window.readOn = function(dest, link) {
    $("#" + dest).show(200);
    return $(link).hide();
  };

  window.selectedClass = null;

  classSelectChanged = [];

  setClass = function(newClass) {
    var f, i, len;
    console.log('setClass:', newClass);
    $('.class-' + window.selectedClass).removeClass('class-selected');
    window.selectedClass = newClass;
    localStorage.setItem('selectedClass', window.selectedClass);
    $('.class-value').val(window.selectedClass);
    $('.class-' + window.selectedClass).addClass('class-selected');
    for (i = 0, len = classSelectChanged.length; i < len; i++) {
      f = classSelectChanged[i];
      f(window.selectedClass);
    }
  };

  window.onClassSelectChanged = function(f) {
    if (window.selectedClass != null) {
      f(window.selectedClass);
    }
    return classSelectChanged.push(f);
  };

  $('document').ready(function() {
    var classSelect, classes;
    window.selectedClass = localStorage.getItem('selectedClass');
    classes = [];
    window.classNames = {};
    $('#class-select option').each(function(v, a) {
      classes.push($(a).prop('value'));
      return window.classNames[$(a).prop('value')] = $(a).text().trim();
    });
    if ((window.selectedClass == null) || classes.indexOf(window.selectedClass) === -1) {
      window.selectedClass = classes[0];
    }
    classSelect = $('#class-select');
    classSelect.val(window.selectedClass);
    setClass(window.selectedClass);
    return classSelect.on('change', function() {
      setClass(this.value);
    });
  });

}).call(this);
