// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    window.app = new Vue({
      el: "#vue-root",
      data: {
        cclass: null,
        categories: categories
      },
      computed: {
        maxCategoryNum: function() {
          return _.max(categories.map(function(c) {
            return c.num;
          }));
        },
        currentPoints: function() {
          return Math.round(_.last(this.cclass.points) * 10) / 10;
        },
        nextMilestone: function() {
          var bigger;
          bigger = milestones.filter((function(_this) {
            return function(m) {
              return m.points > _this.currentPoints;
            };
          })(this));
          if (bigger.length === 0) {
            return "--";
          }
          return Math.round((_.min(bigger.map(function(b) {
            return b.points;
          })) - this.currentPoints) * 10) / 10;
        }
      },
      methods: {
        calcBgWidth: function(num) {
          return _.max([num / this.maxCategoryNum * 90, 13]);
        }
      }
    });
    return onClassSelectChanged(function(c) {
      if (c === "default") {
        app.cclass = null;
      } else {
        app.cclass = _.find(classes, {
          id: +c
        });
      }
    });
  });

}).call(this);
