// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    return onClassSelectChanged(function(c) {
      var classData;
      if (c === "default") {
        return;
      }
      classData = _.find(classes, {
        id: +c
      });
      $("#class-name").text(classData.name);
    });
  });

}).call(this);
