// Generated by CoffeeScript 1.9.1
var classChange;

classChange = function() {
  var challenge, i, len, ref, results;
  $("#challenges").empty();
  ref = challenges[$("#class").val()];
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    challenge = ref[i];
    results.push($("#challenges").append($("<option></option>").attr("value", challenge.id).text(challenge.name)));
  }
  return results;
};

setTimeout(function() {
  classChange();
  return $("#class").change(classChange);
}, 0);
